export const BASE_URL: string;
export const BROWSE_URL: string;
export const DETAIL_URL: string;
export const IMAGE_URL: string;
export const WATCH_URL: string;
export const SEARCH_URL: string;
export const GENRE_URL: string;
export const GENRES: string[];
export const JIKAN_URL: string;
